### ISSUE TITLE
Where to add the API key

### ISSUE THREAD

**Issue by ThomLSA** [gohiring/cachet-status#5]
Hello, i want to use this but i'm wondering where to add the API key

**Comment by ThomLSA** [comment]
**ERROR**:
GET /api/components 404 (Not Found)
Request.init @ cachet-status.js?ver=1.0.0:56
Request @ cachet-status.js?ver=1.0.0:38
CachetStatus.init @ cachet-status.js?ver=1.0.0:16
CachetStatus @ cachet-status.js?ver=1.0.0:3
(anonymous) @ index.php:367
index.php:1 XMLHttpRequest cannot load /api/components. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin '..' is therefore not allowed access. The response had HTTP status code 404.
VM4873:1 Uncaught SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at Request.onError (cachet-status.js?ver=1.0.0:72)
    at XMLHttpRequest.xhr.onerror (cachet-status.js?ver=1.0.0:53)

**Comment by jacobwoffenden** [comment]
Hi @ThomLSA,

`cachet-status` doesn't require an API key as it just looks at the publicly available part of the API.

Also, are you using the latest version? I ask because the API endpoint is `/api/v1/components` and not `/api/components`

Thanks,

**Comment by ThomLSA** [comment]
@jacoblw 
Thanks for the fast reply,
Yes i'm, using the newest version of Cachet, so i can change that url and it must be working?

EDIT: I changed /api/components to /api/v1/components, next error:
cachet-status.js?ver=1.0.0:25 Uncaught TypeError: data[i].status.toLowerCase is not a function
    at cachet-status.js?ver=1.0.0:25
    at Request.onLoad (cachet-status.js?ver=1.0.0:64)
    at XMLHttpRequest.xhr.onload (cachet-status.js?ver=1.0.0:52)
﻿

**Comment by jacobwoffenden** [comment]
@ThomLSA - I meant are you using the latest version of `gohiring/cachet-status`?

Your error:
```
GET /api/components 404 (Not Found)
Request.init @ cachet-status.js?ver=1.0.0:56
Request @ cachet-status.js?ver=1.0.0:38
CachetStatus.init @ cachet-status.js?ver=1.0.0:16
CachetStatus @ cachet-status.js?ver=1.0.0:3
(anonymous) @ index.php:367
index.php:1 XMLHttpRequest cannot load /api/components. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin '..' is therefore not allowed access. The response had HTTP status code 404.
VM4873:1 Uncaught SyntaxError: Unexpected end of JSON input
at JSON.parse ()
at Request.onError (cachet-status.js?ver=1.0.0:72)
at XMLHttpRequest.xhr.onerror (cachet-status.js?ver=1.0.0:53)
```
Note the lines:
`GET /api/components 404 (Not Found)` 
`index.php:1 XMLHttpRequest cannot load /api/components. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin '..' is therefore not allowed access. The response had HTTP status code 404.`

On https://github.com/gohiring/cachet-status/blob/master/src/cachet-status.js#L7 it looks at `/api/v1/components` - What is your `endpointPath`?

**Comment by ThomLSA** [comment]
Got it fixed, thanks!

**Comment by soulim** [comment]
Oooookay 😄 Then I'm closing the issue. Thank you for help @jacoblw!

Have a nice day @ThomLSA and @jacoblw!
